---
title: "Table of contents"
output:
  html_document:
    toc: true
    toc_depth: 2
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include = FALSE}
# README
# required files:
# Model1Baseline_Ysim.xlsx ( to load simulated dependent variable )
# Model1Baseline_Fit.rds ( to load model fit )

# if necessary, manually adjust descriptive statistics and
# data simulation section
```


# Color coding
* <span style="color: blueviolet;">blueviolet</span> for constant and trend component parameters
* <span style="color: deeppink;">deeppink</span> for predicted dependent variable
* <span style="color: orange;">orange</span> for simulated parameters and observed dependent variable


# Descriptive statistics
* $N = 200$

* $T = 10$


# Data simulation
* $y^{obs}_{n,t} \sim Normal(6 + 1 \, x_{n,t},0.75) \quad \text{for } n = 1,...,N$


```{r, include = FALSE}
# preparation ####
# set working directory
setwd("C:/Users/Diiim/Documents/ResearchAssistance")

# set decimals to digits instead of scientific
options(scipen = 999)

# load packages
library(readxl)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)


# estimated data ####
# load model fit
m_fit <- readRDS("SimulationStudyResult/Model1Baseline_Fit.rds")
m_fit_params <- rstan::extract(m_fit)

# predicted dependent variable
Y_pred <- m_fit_params$Y_pred

# number of individuals
N <- dim(Y_pred[1,,])[1]

# number of time periods
no_periods <- dim(Y_pred[1,,])[2]

# time periods
time_periods <- 0:(no_periods-1)
X <- matrix(data = time_periods, nrow = N, ncol = no_periods, byrow = TRUE)

# middle 90% credible intervals for Y_pred
Y_pred_CI_lower <- matrix(data = 0, nrow = N, ncol = no_periods)
Y_pred_CI_upper <- matrix(data = 0, nrow = N, ncol = no_periods)
for (t in 1:no_periods) {
  for (n in 1:N) {
    Y_pred_CI_lower[n,t] <- quantile(Y_pred[,n,t], prob = 0.05)
    Y_pred_CI_upper[n,t] <- quantile(Y_pred[,n,t], prob = 0.95)
  }
}


# simulated data ####
# simulated constant
beta_0_sim <- 6

# simulated linear trend component
beta_1_sim <- 1

# simulated standard deviation for Normal distributions
sigma_sim <- 0.75

# load observed dependent variable
Y_obs <- data.frame(read_excel("SimulationStudyData/Model1Baseline_Yobs.xlsx",
                               sheet = "Sheet 1"))


# colors ####
pink_transp <- rgb(red = 255,
                   green = 20,
                   blue = 147,
                   max = 255,
                   alpha = 25,
                   names = "deeppink1")
```


# Trace plots
```{r}
# constant
plot(m_fit_params$beta_0,
     type = "l",
     col = "blueviolet",
     main = "",
     xlab = "",
     ylab = "")

grid(nx = NA, ny = NULL)
par(new = TRUE)

plot(m_fit_params$beta_0,
     type = "l",
     col = "blueviolet",
     main = "Constant",
     xlab = "Sampling iteration",
     ylab = "beta_0")
```


```{r}
# linear trend component
plot(m_fit_params$beta_1,
     type = "l",
     col = "blueviolet",
     main = "",
     xlab = "",
     ylab = "")

grid(nx = NA, ny = NULL)
par(new = TRUE)

plot(m_fit_params$beta_1,
     type = "l",
     col = "blueviolet",
     main = "Linear trend component",
     xlab = "Sampling iteration",
     ylab = "beta_1")
```


```{r}
# standard deviation for Normal distributions
plot(m_fit_params$sigma,
     type = "l",
     col = "blueviolet",
     main = "",
     xlab = "",
     ylab = "")

grid(nx = NA, ny = NULL)
par(new = TRUE)

plot(m_fit_params$sigma,
     type = "l",
     col = "blueviolet",
     main = "Standard deviation for Normal distributions",
     xlab = "Sampling iteration",
     ylab = "sigma")
```


# Posterior
```{r}
# constant
hist(m_fit_params$beta_0,
     xlim = c(min(m_fit_params$beta_0,beta_0_sim),
              max(m_fit_params$beta_0,beta_0_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "",
     xlab = "")

grid()
par(new = TRUE)

hist(m_fit_params$beta_0,
     xlim = c(min(m_fit_params$beta_0,beta_0_sim),
              max(m_fit_params$beta_0,beta_0_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "Constant",
     sub = "( the orange line shows the simulated parameter value )",
     xlab = "beta_0")
abline(v = beta_0_sim,
       lwd = 2,
       col = "orange")
box()
```


```{r}
# linear trend component
hist(m_fit_params$beta_1,
     xlim = c(min(m_fit_params$beta_1,beta_1_sim),
              max(m_fit_params$beta_1,beta_1_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "",
     xlab = "")

grid()
par(new = TRUE)

hist(m_fit_params$beta_1,
     xlim = c(min(m_fit_params$beta_1,beta_1_sim),
              max(m_fit_params$beta_1,beta_1_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "Linear trend component",
     sub = "( the orange line shows the simulated parameter value )",
     xlab = "beta_1")
abline(v = beta_1_sim,
       lwd = 2,
       col = "orange")
box()
```


```{r}
# standard deviation for Normal distributions
hist(m_fit_params$sigma,
     xlim = c(min(m_fit_params$sigma,sigma_sim),
              max(m_fit_params$sigma,sigma_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "",
     xlab = "")

grid()
par(new = TRUE)

hist(m_fit_params$sigma,
     xlim = c(min(m_fit_params$sigma,sigma_sim),
              max(m_fit_params$sigma,sigma_sim)),
     col = "blueviolet",
     border = FALSE,
     main = "Standard deviation for Normal distributions",
     sub = "( the orange line shows the simulated parameter value )",
     xlab = "sigma")
abline(v = sigma_sim,
       lwd = 2,
       col = "orange")
box()
```


# Posterior predictive check via middle 90% credible interval
```{r}
for (n in 1:N) {
  y_upper <- Y_pred_CI_upper[n,]
  y_lower <- Y_pred_CI_lower[n,]
  x <- X[n,]
  
  plot(x = x,
       y = c(max(y_upper),
             min(y_lower),
             max(Y_obs[n,]),
             min(Y_obs[n,]),
             rep(max(y_upper), times = no_periods-4)),
       type="l",
       col = "white",
       main = paste("Individual n =", n),
       sub = "( the orange line shows the observed dependent variable )",
       xlab = "t",
       ylab = "Y_pred")
  
  grid(nx = NA, ny = NULL)
  par(new = TRUE)
  
  polygon(x = c(x, rev(x)),
          y = c(y_upper, rev(y_lower)),
          col = pink_transp,
          lty = 0)
  lines(x = x,
        y = Y_obs[n,],
        lwd = 2,
        col = "orange")
  box()
}
```


