---
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: TRUE
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include = FALSE}
# set working directory
setwd("C:/Users/Diiim/Documents/GitHub/BayesianGMMs")

# set decimals to digits instead of scientific
options(scipen = 999)

# load packages
library(flextable)
```


# Methodology
Convergence and estimation stability are measured by the number of successful NUTS estimation runs in relation to the total number of runs.

# Model 1
```{r}
# model
m <- c("baseline",
       "two classes",
       "three classes",
       "two classes",
       "two classes",
       "two classes",
       "three classes")

# model_modification
m_mod <- c("-",
           "-",
           "-",
           "identically distributed errors",
           "identically distributed errors",
           "identically distributed errors",
           "identically distributed errors")

# simulation case
sim_case <- c("1",
              "2",
              "5",
              "16",
              "17",
              "18",
              "19")

# observed_dependent_variable
Y_obs <- c("Yobs",
           "Yobs",
           "Yobs",
           "Yobslog",
           "Yobslog",
           "Yobslog",
           "Yobslog")

# convergence stability
conv_stab <- c("5 / 5",
               "4 / 5",  # convergence warnings for simulation run 3
               "1 / 5",
               # convergence warnings for simulation runs 1, 2, 4, and 5
               
               "2 / 5",  # convergence warnings for simulation runs 3, 4, and 5
               "1 / 5",
               # convergence warnings for simulation runs 1, 2, 3, and 5
               
               "5 / 5",
               "1 / 5"
               # convergence warnings for simulation runs 1, 2, 4, and 5
               )

# estimation stability 
est_stab <- c("5 / 5",
              "4 / 5",
              "1 / 5",
              "2 / 5",
              "1 / 5",
              "5 / 5",
              "1 / 5")

# table
df <- data.frame(m,
                 m_mod,
                 sim_case,
                 Y_obs,
                 conv_stab,
                 est_stab)

# column names for table
names(df) <- c("Model",
               "Model modification",
               "Simulation case",
               "Observed dependent variable",
               "Convergence stability",
               "Estimation stability")

# print table
flextable(df)
```


# Model 2
```{r}
# model
m <- c("baseline",
       "two classes",
       "three classes")

# model_modification
m_mod <- c("-",
           "-",
           "-")

# dataset
sim_case <- c("8",
              "9",
              "12")

# observed_dependent_variable
Y_obs <- c("Yobs",
           "Yobs",
           "Yobs")

# convergence stability
conv_stab <- c("5 / 5",
               "4 / 5",  # convergence warnings for simulation run 1
               "2 / 5"
               # convergence warnings for simulation runs 2, 3, and 4
               )

# estimation stability
est_stab <- c("5 / 5",
              "4 / 5",
              "2 / 5")

# table
df <- data.frame(m,
                 m_mod,
                 sim_case,
                 Y_obs,
                 conv_stab,
                 est_stab)

# column names for table
names(df) <- c("Model",
               "Model modification",
               "Simulation case",
               "Observed dependent variable",
               "Convergence stability",
               "Estimation stability")

# print table
flextable(df)
```


# Model 3
```{r}
# model
m <- c("baseline",
       "two classes",
       "two classes",
       "two classes",
       "three classes")

# model_modification
m_mod <- c("-",
           "-",
           "-",
           "-",
           "-")

# dataset
sim_case <- c("15",
              "16",
              "17",
              "18",
              "19")

# observed_dependent_variable
Y_obs <- c("Yobs",
           "Yobs",
           "Yobs",
           "Yobs",
           "Yobs")

# convergence stability
conv_stab <- c("5 / 5",
               "5 / 5",
               "5 / 5",
               "5 / 5",
               "5 / 5")

# estimation stability
est_stab <- c("5 / 5",
              "5 / 5",
              "5 / 5",
              "5 / 5",
              "5 / 5")

# table
df <- data.frame(m,
                 m_mod,
                 sim_case,
                 Y_obs,
                 conv_stab,
                 est_stab)

# column names for table
names(df) <- c("Model",
               "Model modification",
               "Simulation case",
               "Observed dependent variable",
               "Convergence stability",
               "Estimation stability")

# print table
flextable(df)
```


# Model 5
```{r}
# model
m <- c("two classes",
       "three classes")

# model_modification
m_mod <- c("-",
           "-")

# dataset
sim_case <- c("29",
              "32")

# observed_dependent_variable
Y_obs <- c("Yobs",
           "Yobs")

# convergence stability
conv_stab <- c("5 / 5",
               "... / ...")

# estimation stability
est_stab <- c("5 / 5",
              "... / ...")

# table
df <- data.frame(m,
                 m_mod,
                 sim_case,
                 Y_obs,
                 conv_stab,
                 est_stab)

# column names for table
names(df) <- c("Model",
               "Model modification",
               "Simulation case",
               "Observed dependent variable",
               "Convergence stability",
               "Estimation stability")

# print table
flextable(df)
```


